/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <div className="flex">
            <div className="w-[100px] ">
              <Sidebar />
            </div>
            <div className="ml-10 w-4/5 ">
              <Topbar />
            </div>
            <div className="w-1/5 flex flex-row-reverse justify-center items-center">
              <img
                src="https://duaruqyah.com/assets/settings/profile.svg"
                alt="profile"
              />
            </div>
          </div>
          <div className="ml-32  flex gap-5">
            <Navbar />
            <div className="w-[60%] mt-14 h-[calc(100vh_-_17.5vh)] scrl pb-6 pt-14 col-start-2  delay-1000 transition duration-1000 ease-linear  ">
              {children}
            </div>
            <div className="bg-white dark:bg-dark-bg w-[20%] rounded-3xl  pb-16  mt-14 h-[calc(100vh_-_17.5vh)]  ">
              <div className="flex justify-center items-center p-10">
                <p className=" text-2xl text-gray-500">Settings</p>
              </div>
              <div className="flex flex-col gap-10"></div>
              <SideCard
                title="Language Settings"
                image="https://duaruqyah.com/assets/sidebar/language.svg"
              />
              <SideCard
                title="General Settings"
                image="https://duaruqyah.com/assets/sidebar/general.svg"
              />
              <SideCard
                title="Font Settings"
                image="https://duaruqyah.com/assets/sidebar/font.svg"
              />
              <SideCard
                title="Appearance Settings"
                image="https://duaruqyah.com/assets/sidebar/font.svg"
              />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}

export default RootLayout;

function SideCard({ title, image }: any) {
  return (
    <>
      <div className="mx-4 my-4">
        <div className="">
          <div className="cursor-pointer">
            <div className="bg-gray-100 flex flex-row w-full rounded-lg dark:bg-dark-bg-dark">
              <div className=" w-1 rounded-tl-lg rounded-bl-lg"></div>
              <div className="p-2 flex flex-row items-center w-full">
                <div className="bg-gray-200 flex p-2 items-center rounded-full mr-5 justify-center dark:bg-dark-bg ">
                  <img src={image} alt="general" />
                </div>
                <p className="text-gray-500 dark:text-dark-text  text-start text-base leading-5 xs:text-sm lg-min:text-sm style-Kalpurush">
                  {title}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
